### ISSUE TITLE
Add watchdog support (timeout)

### ISSUE THREAD

**Issue by fedotxxl** [fracpete/rsync4j#1]
rsync process may consume too much time. In this case, it should be killed. I suggest you add this feature (you may use org.apache.commons.exec.ExecuteWatchdog)

**Comment by fracpete** [comment]
Good idea. I added the `--maxtime` option (time in seconds), which kills the rsync process once reached. Ignored if less than 1 (default is -1). Just released a new version: 3.1.2-5
