### ISSUE TITLE
rsync://[USER@]HOST[:PORT]/SRC not working on Windows via API

### ISSUE THREAD

**Issue by schwitters** [fracpete/rsync4j#10]
The following setup does not work on plain-protocol rsync servers :
 RSync rsync = new RSync()
 				  .recursive(true)
				  .times(true)
				  .dirs(true)
				  .verbose(true)
				  .rsh(null)
				  .passwordFile("C:\\tmp\\somepwfile")
				  .source("rsync://user@server/dir/dir1/")
				  .destination("c:\\tmp\\dir1")
....
It should be possible to disable rsh command.
..
.rsh(null)
..
leads to a NPE. 

Possible solution :
  - allow .rsh(null)
  - do not add --rsh= if getRsh()==null

**Comment by fracpete** [comment]
Good point! I've aligned the behavior under Windows to other platforms:
default or `rsh("")` will use plain protocol, `rsh("ssh")` will use the built-in ssh binary.
Release 3.1.2-15 contains this fix.
