### ISSUE TITLE
How to use Java code to copy files from/to remote Windows machines

### ISSUE THREAD

**Issue by pajelonek** [fracpete/rsync4j#13]
Hi,

I have two Windows machines and I wanted to set-up rsync4j in that way that rsync will synchronize my files automatically.

Is there a way to make rsync work on two windows machines? From your documentation, it seems like it but on the other hand, rsync daemon is Linux based and I don't think it would work. Using ssh with keys will allow such connection?

Thanks in advance

**Comment by fracpete** [comment]
No problem with syncing between two Windows machines. You can sync directory `C:\some\dir` on the local machine to `C:\other\dir` on remote host `otherbox` by using UNC paths in Cywgin notation:
* source: `/cygdrive/c/some/dir/`
* destination: `//otherbox/C$/other/dir`

**Comment by pajelonek** [comment]
`otherbox`  is a hostname from ssh-config after setting-up ssh-keys? From what I understand, UNC paths are possible here if my destination is a shared folder, which I can't set up. I have two completely not related Windows machines where I can only sync them by choosing a folder to send data by sync. That's why I don't get how to acquire `otherbox` name, sorry I am kinda dummy about networking.

**Comment by fracpete** [comment]
If you want to use ssh, you need to have ssh running on the other machine. You can run an openssh server via cygwin on Windows.
The UNC paths are if there is trust between the machines, I believe. C$ etc are special shares. `otherbox` can be the Windows name or ip address, if I remember correctly.

**Comment by pajelonek** [comment]
I will try this and let u know.
Thanks for your help.

**Comment by pajelonek** [comment]
Hi again,
I tried some ideas like sharing folder to sshd on Windows 10 and as you suggested by special shares to the folder and every time I receive "rsync is not recognized as an internal or external command". Do you have any other ideas about what can I do in this situation?

**Comment by fracpete** [comment]
Yoi have to tell me more about your environment. Are you using rsync4j from within your Java application (what dependency did you include) or as standalone command line tool? Did you install cygwin on the other machine after all, to have an openssh server running?

**Comment by pajelonek** [comment]
Topic closed, I had to add rsync.exe to system variables and it solved a problem.

**Comment by fracpete** [comment]
Did you have to do that on the remote Windows machine or the local one?

**Comment by pajelonek** [comment]
On the remote Windows machine. I thought it would be a closed issue but right now I encountered another problem when I wanted to test added ssh through code.

When I run java code with attached ssh binaries:
 
public class RSyncFileUpdaterExecutor { 

    @Value("${ssh.private_key.path}")
    private String sshPrivateKeyPath;

    Logger logger = LoggerFactory.getLogger(RSyncFileUpdaterExecutor.class);

    List<String> sources;
    String destination;
    RSync rSync = new RSync();

    public void execute() {
        try {
            rSync.sources(sources)
                    .debug("ALL")
                    .outputCommandline(true)
                    .destination(destination)
                    .verbose(true)
                    .rsh(Binaries.sshBinary() + " -i " + Binaries.convertPath(sshPrivateKeyPath));

            StreamingProcessOutput output = new StreamingProcessOutput(new RsyncOutput());
            output.monitor(rSync.builder());

            if (output.getExitCode() > 0) {
                throw new Error("Error while executing rsync");
            } else logger.info("Successfully modified {} on server", sources.toString());

        } catch (Exception exception) {
            logger.error(exception.getMessage());
            throw new Error("Caught exception while executing rsync");
        }
    }

I receive:

> [ERR] Permission denied, please try again.

> [ERR] Permission denied, please try again.

> [ERR] pawst@remote_machine_ip: Permission denied (publickey,password,keyboard-interactive).

> [ERR] rsync: connection unexpectedly closed (0 bytes received so far) [sender]

> [ERR] rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]

> [OUT] opening connection using: /cygdrive/c//rsync4j/bin/ssh.exe -l pawst remote_machine_ip rsync --server -ve.LsfxC "--log-format=%i" --debug=ALL . serverFiles/  (11 args)

> [OUT] [sender] _exit_cleanup(code=12, file=io.c, line=226): about to call exit(12)

It looks like a problem with ssh authentication but when I run created command on cmd/Powershell it works fine and transfers files.
The command from rsync pasted on cmd:
> C:\rsync4j\bin\rsync.exe --verbose --debug=ALL --rsh="/cygdrive/c//rsync4j/bin/ssh.exe -i /cygdrive/c//id_rsa" /cygdrive/c//clientFiles/newFile.txt /cygdrive/c//clientFiles/test2.txt /cygdrive/c//clientFiles/test3.txt pawst@remote_machine_ip:serverFiles/

The output from cmd:
newFile.txt
test2.txt
test3.txt
sent 216 bytes  received 85 bytes  602.00 bytes/sec
total size is 43  speedup is 0.14`

Is it some sort of bug? From what I checked deep down your wrapper starts a thread that executes created command so it seems like it should be the same result with cmd/Powershell.

There is also one thing, although rsync with ssh works, it doesn't work without it. When I run with cmd:

> C:\rsync4j\bin\rsync.exe /cygdrive/c//clientFiles/newFile.txt /cygdrive/c//clientFiles/test2.txt /cygdrive/c//clientFiles/test3.txt pawst@remote_machine_ip:serverFiles/

It returns:
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.2]
rsync: safe_read failed to read 4 bytes [sender]: Connection reset by peer (104)
rsync error: error in rsync protocol data stream (code 12) at io.c(276) [sender=3.1.2]

**Comment by pajelonek** [comment]
It seems like I know what the issue is here. In debug we can see that: 
`opening connection using: /cygdrive/c//rsync4j/bin/ssh.exe -l pawst IP rsync --server -ve.LsfxC "--log-format=%i" --debug=ALL . serverFiles/  (11 args)`
so we are trying to connect to ssh without publickey. When I add to this command identity file it works, as well as putting "ssh" instead of path to binary.  @fracpete Do you have any idea how to make this work?

**Comment by fracpete** [comment]
No, unfortunately not. The additional complication is that I don't have access to two Windows machines for testing (I'm Linux only).
Since running the explicit call works for you, maybe instead of using the rsync wrapper, you could just use a batch/powershell file that you call from Java (e.g., using the [processoutput4j](https://github.com/fracpete/processoutput4j) library to capture the output)?

**Comment by pajelonek** [comment]
Topic closed, adding pairs of keys to added ssh binary automatically provided keys.
