### ISSUE TITLE
Issue with using .rsh("ssh -i /path/to/the/certificate")

### ISSUE THREAD

**Issue by alokym86** [fracpete/rsync4j#14]
The following setup
```
String pathToMyOwnCert = "C:\Users\user\.ssh\idftpuser";
RSync rsync = new RSync()
.source("ftpuser@192.168.69.112:~/public_html/version/*")
.destination("./")
.archive(true)
.timeout(15)
.info("progress2");
rsync.rsh(Binaries.sshBinary() + " -i " + Binaries.convertPath(pathToMyOwnCert)
	+ " -o StrictHostKeyChecking=no"
	+ " -p " + 22);
```
returned 
[ERR] Unexpected remote arg: ftpuser@192.168.69.112:~/public_html/version/*
rsync error: syntax or usage error (code 1)

`rsync.rsh("ssh" + " -i " + Binaries.convertPath(pathToMyOwnCert)`;
returned the same

With Release v3.1.2-14 it works perfectly!

**Comment by fracpete** [comment]
That should work again with release `3.1.3-2`.

**Comment by alokym86** [comment]
Unfortunately, it doesn't work. The result is the same as before.

**Comment by fracpete** [comment]
Have you tried:

```java
rsync.rsh("\"" + Binaries.sshBinary() + " -i " + Binaries.convertPath(pathToMyOwnCert)
	    + " -o StrictHostKeyChecking=no"
    	    + " -p " + 22 + "\"");
```

**Comment by alokym86** [comment]
It does not work:
rsync: Failed to exec C:\Users\user\rsync4j\bin\ssh.exe -i /cygdrive/c//Users/user/.ssh/idftpuser -o StrictHostKeyChecking=no -p 22: No such file or directory (2)

But, with masked single quotation marks, it works!
```
rsync.rsh("\'" + Binaries.sshBinary() + " -i " + Binaries.convertPath(pathToMyOwnCert)
	    + " -o StrictHostKeyChecking=no"
    	    + " -p " + 22 + "\'");
```
