### ISSUE TITLE
Version of processoutput4j

### ISSUE THREAD

**Issue by nikkozzblu** [fracpete/rsync4j#25]
Hi @fracpete

I have noticed that rsync4j is still depending on the 0.0.7 version of processoutput4j that is prior to the Apache license addition of this project. Do you think there would be any issue to update the pom reference to 0.0.11 of processoutput4j?

All the best

**Comment by fracpete** [comment]
Considering that rsync4j is GPLv3 as well (rsync itself is GPLv3), having another GPLv3 library like processoutput4j won't have any impact.

**Comment by fracpete** [comment]
Closed due to inactivity
