### ISSUE TITLE
rsync4j in Apache Karaf

### ISSUE THREAD

**Issue by AlexProjectsHub** [fracpete/rsync4j#27]
Hello, 
I would like to use your library in my OSGi project in Apache Karaf. For it to work in my project i'll need to make it compatible by wrapping the library in a Karaf-bundle. 
If you are interested in adding your library to this environment, respond to me, and i'll help you.

**Comment by fracpete** [comment]
Though I don't have much time to work on my personal side-projects these days, please feel free to discuss the necessary changes. If they seem fine by me, then you can open a PR.

**Comment by fracpete** [comment]
closed due to inactivity
