### ISSUE TITLE
Apostrophe in username - Rsync fails

### ISSUE THREAD

**Issue by nate265** [fracpete/rsync4j#30]
RSYNC fails when run from the user home directory with an apostrophe in the user name. Something like O'Reilly.  This is on windows. Workaround is to change RSYNC4J_HOME env.

**Comment by fracpete** [comment]
Interesting. Could you please post the exact error message that you are getting?

**Comment by fracpete** [comment]
Addressed with 02cf342a1931c1a17fbe88e20956ddc63e3ccf1b
