### ISSUE TITLE
Spaces in the users username on a Windows machine

### ISSUE THREAD

**Issue by JoeJones649** [fracpete/rsync4j#31]
We have a user whose username contains a space which results in the rsync command erroring with

rsync: [sender] Failed to exec C:\Users\Joe: No such file or directory (2)
rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.2.4dev]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev]

It seems like you've had another issue with the single quotes, can something similar be implemented for spaces?

**Comment by fracpete** [comment]
Can you provide some more details?

The following worked for me:
* created a user with a space in the name called `joe joe` on a Windows VM
* downloaded release archive [rsync4j-all-3.2.3-10-bin.zip](https://github.com/fracpete/rsync4j/releases/download/rsync4j-pom-3.2.3-10/rsync4j-all-3.2.3-10-bin.zip)
* extracted the release zip file
* changed into dir `C:\Users\joe joe\Downloads\rsync4j-all-3.2.3-10\lib`
* ran the following command successfully
  `C:\Users\joe joe\Downloads\rsync4j-all-3.2.3-10\lib>java -cp ".\*" com.github.fracpete.rsync4j.RSync -r "C:\Users\joe joe\Downloads\rsync4j-all-3.2.3-10\lib" "C:\Users\joe joe\Downloads\target"`

**Comment by JoeJones649** [comment]
Sorry I should have been clearer. When the rsync.exe is installed in the users home directory (which I think is the default) seem like we get the error above then. Is the command you've specified using the rsync.exe binary in the "C:\Users\joe joe" directory?

**Comment by fracpete** [comment]
When adding `--output-commandline`, it shows this:

```
INFO: Command-line: C:\Users\joe joe\rsync4j\bin\rsync.exe --recursive /cygdrive/c/Users/joe joe/Downloads/rsync4j-all-3.2.3-10/lib /cygdrive/c/Users/joe joe/Downloads/target
```
As you can see, rsync executable, source and target directory all have a space.

Can you please provide a minimal example where this problem occurs (including the `--output-commandline` flag)?
Are you using the 3.2.3-10 version (currently latest version)?
Are you using rsync4j from command-line, like I did, or are you using it from your Java code?

**Comment by fracpete** [comment]
Due to inactivity
