### ISSUE TITLE
Make rsync path customizable

### ISSUE THREAD

**Issue by tklinchik** [fracpete/rsync4j#33]
I think it would be desirable to make rsync path customizable so by default on Linux/Mac it would use /usr/bin/rsync but would give user an option to override.

**Comment by fracpete** [comment]
Do you have a use case where the location is different?

**Comment by tklinchik** [comment]
Unfortunately I do. Tried using it on Mac but rsync that comes with OSX is very dated so doesn't support some of the features such as chown, chmod, etc. OSX way of upgrading it is using brew and therefore leaving /usr/bin/rsync untouched and creating a new one elsewhere (/usr/local/bin/rsync).
I think either a manual override or simply deriving location from environment aka `which rsync` or simply using `rsync` would suffice. The later might even make more sense.
Consideration much appreciated.

**Comment by fracpete** [comment]
The simplest would be using environment variables, which override the default locations of the binaries in `/usr/bin`:

* `RSYNC4J_RSYNC`
* `RSYNC4J_SSH`
* `RSYNC4J_SSHPASS`
* `RSYNC4J_SSHKEYGEN`

That should be sufficient from my understanding.

**Comment by tklinchik** [comment]
That would do it too.
Any reason to use hardcoded /usr/bin/ path as opposed to just `rsync` or `ssh`, etc?

**Comment by fracpete** [comment]
I had problems in the past when launching processes if I didn't use an absolute path to the binary.

**Comment by fracpete** [comment]
Implemented with 95279c099bd8eac6ed6a1abdc7ca7b72fa8f8ad1.

**Comment by fracpete** [comment]
Just released [3.2.3-12](https://github.com/fracpete/rsync4j/releases/tag/rsync4j-pom-3.2.3-12).

**Comment by tklinchik** [comment]
That's awesome. Thanks for a quick turnaround.
