### ISSUE TITLE
add support to parallel transfer

### ISSUE THREAD

**Issue by shyding** [fracpete/rsync4j#34]
Concurrent transmission is necessary. Is it possible to add concurrent features?

**Comment by fracpete** [comment]
rsync4j is just a wrapper around the rsync binary, which itself does not use concurrent transmissions. However, if you have multiple top-level directories to sync, then you could just launch multiple rsync4j threads that do the sync. Something similar can be done on the command-line using [xargs](https://stackoverflow.com/questions/24058544/speed-up-rsync-with-simultaneous-concurrent-file-transfers).
