### ISSUE TITLE
How to Use Rsync4j with Non-Standard Port

### ISSUE THREAD

**Issue by shyding** [fracpete/rsync4j#35]

**Comment by shyding** [comment]
current just support  ssh 22 port

**Comment by fracpete** [comment]
Have you tried the `RSync.port(int)` method to set the non-standard port? Uses the `--port` option under the hood.
Alternatively, use the `RSync.rsh(String)` method to set a custom `ssh` command, something like `/usr/bin/ssh -p 1022`.

**Comment by shyding** [comment]
yes I did , when I try "RSync.rsh(String)  like this /usr/bin/ssh -p 1022" , exception: rsync  cant exec  /usr/bin/ssh -p 1022, no such file or directory .  my  case is on rsync on ssh , not just rsync, so  I don't  try RSync.port(int) .

**Comment by shyding** [comment]
you can try  the standard port 22 of ssh , change 23 , timeout should be excepted .

**Comment by shyding** [comment]
信息: Command-line: C:\Users\dsy\rsync4j\bin\sshpass.exe -p test -v C:\Users\dsy\rsync4j\bin\rsync.exe --debug=ALL --archive --recursive --rsh="ssh  -p 22" --progress youibot@100.0.600.15:/home/youibot/youibot_map /cygdrive/d/test/other/place
[sender] _exit_cleanup(code=1, file=main.c, line=1508): about to call exit(1)
[sender] send_msg_int(86, 1)
Unexpected remote arg: youibot@10.0.60.15:/home/youibot/youibot_map
rsync error: syntax or usage error (code 1) at main.c(1508) [sender=3.2.7]

**Comment by shyding** [comment]
![image](https://github.com/fracpete/rsync4j/assets/24986567/fefdd0de-99f8-4f1a-bf64-db42989ba634)


`	
    String src = "/home/test/test/";
	@Test
	public void test5() throws Exception {
		
		
		RSync rsync = new RSync()
				.debug("ALL")
//				.rsh("ssh "+" -p " + 22 +"-l "+ userName + "")
				.rsh("ssh")
//				 
				   .sshPass( sshPass)
				 
				  .source( userName +"@"+ host + ":" + src   )
				  .destination("d:/test/other/place/")
				  .progress(true)
				  .recursive(true)
//				  .archive(true)
				  .outputCommandline(true)
				  .additional("")
				  ;
				ConsoleOutputProcessOutput output = new ConsoleOutputProcessOutput();
				output.monitor(rsync.builder());
			
				System.out.println(output.getExitCode());
	}
`

**Comment by fracpete** [comment]
From your original post it wasn't obvious that you are on Windows. `/usr/bin/ssh` is the location of the ssh binary under Linux (I'm running Linux).

Have a look at the documentation below for specifying the ssh binary under Windows with custom arguments:
https://fracpete.github.io/rsync4j/java/#windows

Instead of the identify parameter `-i` from the example plug in your `-p PORT` option.

**Comment by shyding** [comment]
@Test
	public void test5() throws Exception {
		

		RSync rsync = new RSync()
				.debug("ALL")
       .rsh(Binaries.sshBinary() + " -i " + Binaries.convertPath("D:\\\\test\\\\other\\\\key\\\\testkey\\testkey.pub") + " -p " + 22 +"-l "+ userName + "")
	
		.sshPass( sshpass)
		  .source( userName +"@"+ host + ":" + src   )
		  .destination("d:/test/other/place/")
		  .progress(true)
		  .recursive(true)
		// .archive(true)
		.outputCommandline(true)
		
		;
		ConsoleOutputProcessOutput output = new ConsoleOutputProcessOutput();
		output.monitor(rsync.builder());
	
					System.out.println(output.getExitCode());
	}

Unexpected remote arg: test@10.0.60.15:/home/youibot/ta/
[sender] _exit_cleanup(code=1, file=main.c, line=1508): about to call exit(1)
[sender] send_msg_int(86, 1)
rsync error: syntax or usage error (code 1) at main.c(1508) [sender=3.2.7]
1
 
**have tried, but have another error** 

![image](https://github.com/fracpete/rsync4j/assets/24986567/25ccc635-d2bd-41ea-b830-f99d5b0488ad)

**Comment by shyding** [comment]
![image](https://github.com/fracpete/rsync4j/assets/24986567/d213a055-65d7-4619-95e1-f8b2364e16bd)

the above is also  the same error .

**Comment by shyding** [comment]
also :
![image](https://github.com/fracpete/rsync4j/assets/24986567/11e4aef4-0a3e-434d-841a-3198a7e29cc7)

**Comment by shyding** [comment]
This kind of error occurs under the windows system but does not occur under linux

**Comment by fracpete** [comment]
> ```
>     @Test
> public void test5() throws Exception {
> 	
> 
> 	RSync rsync = new RSync()
> 			.debug("ALL")
>    .rsh(Binaries.sshBinary() + " -i " + Binaries.convertPath("D:\\\\test\\\\other\\\\key\\\\testkey\\testkey.pub") + " -p " + 22 +"-l "+ userName + "")
> 
> 	.sshPass( sshpass)
> 	  .source( userName +"@"+ host + ":" + src   )
> 	  .destination("d:/test/other/place/")
> 	  .progress(true)
> 	  .recursive(true)
> 	// .archive(true)
> 	.outputCommandline(true)
> 	
> 	;
> 	ConsoleOutputProcessOutput output = new ConsoleOutputProcessOutput();
> 	output.monitor(rsync.builder());
> 
> 				System.out.println(output.getExitCode());
> }
> ```
> 
> Unexpected remote arg: test@10.0.60.15:/home/youibot/ta/ [sender] _exit_cleanup(code=1, file=main.c, line=1508): about to call exit(1) [sender] send_msg_int(86, 1) rsync error: syntax or usage error (code 1) at main.c(1508) [sender=3.2.7] 1
> 
> **have tried, but have another error**
> 
> ![image](https://user-images.githubusercontent.com/24986567/250425427-25ccc635-d2bd-41ea-b830-f99d5b0488ad.png)

You are missing a leading space with the `-l` option. The generated string has no space between the port number `22` and `-l`.

I thought you were using a non-default port? 22 is the default port for ssh.

**Comment by shyding** [comment]
Althogh I add a leading space  , the errors still occours . Yes I  were using a non-default port. . 22 is to be changed to another port .

 as follows :

        @Test
	public void test5() throws Exception {
		

		RSync rsync = new RSync()
				.debug("ALL")
       .rsh(Binaries.sshBinary() + " -p " + 22 +"  -l  "+ userName + " ")
	
		.sshPass( sshpass)
		  .source( userName +"@"+ host + ":" + src   )
		  .destination("d:/test/other/place/")
		  .progress(true)
		  .recursive(true)
		// .archive(true)
		.outputCommandline(true)
		
		;
		ConsoleOutputProcessOutput output = new ConsoleOutputProcessOutput();
		output.monitor(rsync.builder());
	
					System.out.println(output.getExitCode());
	}
	

	@Test
	public void test6() throws Exception {
		

		RSync rsync = new RSync()
				.debug("ALL")
       .rsh(Binaries.sshBinary() + " -p " + 22 + " ")
	
		.sshPass( sshpass)
		  .source( userName +"@"+ host + ":" + src   )
		  .destination("d:/test/other/place/")
		  .progress(true)
		  .recursive(true)
		// .archive(true)
		.outputCommandline(true)
		
		;
		ConsoleOutputProcessOutput output = new ConsoleOutputProcessOutput();
		output.monitor(rsync.builder());
	
					System.out.println(output.getExitCode());
	}

![image](https://github.com/fracpete/rsync4j/assets/24986567/f1fa47b3-72ba-47e9-93eb-7c627107550e)

**Comment by sgregori** [comment]
Hi friends,

It worked for me on Linux using a standard .ssh/config file with Port value like this:

```
Host vac
     hostname xx.xx.xx.xx
     port 2222
```


Regards.

**Comment by shyding** [comment]
Thus you've changed the ssh's client config of  the linux system. What's I want is to change  junst an  application.

**Comment by fracpete** [comment]
Apologies for the late reply, I have been busy with other projects. 

There were two problems:
1. The `sshPass` instance was used on the outer `rsync` binary, but had to be used on the `ssh` binary that is part of the `--rsh` option.
2. The `--rsh` option was assembled via concatenation using `--rsh=CMD`, which wasn't very reliable with quoting.

I've just pushed out a new release [3.2.7-2](https://github.com/fracpete/rsync4j/releases/tag/rsync4j-pom-3.2.7-2), which fixes the problem with `--rsh`. It also introduced the `commandLine()` method to classes derived from `AbstractBinary`, which returns the full command-line as a single string (the `commandLineArgs` method returned a list, which still needed to be flattened).

In the example below (which I ran successfully at my end), the `--rsh` option gets assembled from concatenating the command-lines of `sshPass` and `ssh`:

```java
import com.github.fracpete.processoutput4j.output.ConsoleOutputProcessOutput;
import com.github.fracpete.rsync4j.RSync;
import com.github.fracpete.rsync4j.Ssh;
import com.github.fracpete.rsync4j.SshPass;
import com.github.fracpete.rsync4j.core.Binaries;

public class RSyncTest {
  public static void main(String[] args) throws Exception {
    String userName = "USER";
    SshPass sshpass = new SshPass()
      .password("PASSWORD");
    Ssh ssh = new Ssh()
      .port(22)
      .option("StrictHostKeyChecking=no", "PubKeyAuthentication=no");
    String host = "192.168.1.100";
    String src = "/some/remote/dir";
    RSync rsync = new RSync()
      .rsh(sshpass.commandLine() + " " + ssh.commandLine())
      .source(userName + "@" + host + ":" + src)
      .destination("C:/some/local/dir/")
      .recursive(true)
      .verbose(true)
      .outputCommandline(true);
    ConsoleOutputProcessOutput output = new ConsoleOutputProcessOutput();
    output.monitor(rsync.builder());

    System.out.println(output.getExitCode());
  }
}
```

**Comment by sgregori** [comment]
> Thus you've changed the ssh's client config of the linux system. What's I want is to change junst an application.

You can add an invented host name in .ssh/config for the specific application, is not needed to use the real host name in the config.

Per example, supposing that the real hostname is an ip address or domain name, you can set a short name invented in the config, and setting the ip or domain in the "hostname" variable.

This is a trick that i used for a scenario with an application that i can't change the source code, but internally uses this rsync library for the connection.

Regards.

**Comment by fracpete** [comment]
Assumed to be working now with latest released.
