### ISSUE TITLE
Is rsync copy only updated block of a file OR the whole file when file is exist on destination ? (Java jar)

### ISSUE THREAD

**Issue by akashcse** [fracpete/rsync4j#37]

**Comment by fracpete** [comment]
According to the Wikipedia entry on [rsync](https://en.wikipedia.org/wiki/Rsync#Determining_which_parts_of_a_file_have_changed), the file gets split into chunks and a rolling checksum is used to determine whether chunks need to be transmitted since they are different.

**Comment by akashcse** [comment]
@fracpete  thanks for the reply.
Is it possible to sync files from server1 to server2 by running java application(using jar) from server3?
Note: server1 and server2 doesn't has rsync installed.

**Comment by fracpete** [comment]
No, when using the Java application.
Yes, when using ssh from the local machine via a reverse channel (see [here](https://unix.stackexchange.com/questions/183504/how-to-rsync-files-between-two-remotes)). But be aware of the [security implications](https://unix.stackexchange.com/a/247135).
