### ISSUE TITLE
Cannot use path like 'rsync://...' on Windows Machines

### ISSUE THREAD

**Issue by fcyron** [fracpete/rsync4j#39]
Hi,

unless I'm doing something wrong, java code like this:

RSync rsync = new RSync()
          .source("c:\tmp\myfile.txt")
          .destination("rsync://localhost:21234/someDir/")
          .recursive(false);

does not run on windows machines anymore since version (I think) 3.2.3-10, because it seems that you changed the way paths are converted on windows. In my example above 'rsync://localhost:21234/...' is converted to 'rsync:/localhost..." (or '//localhost:2134...' is converted to 'localhost:2134...') and then the rsync command fails with exit code 12.

Is there some way around this? I need to transparently use the tool on linux and windows machines, so I do not want to adjust paths myself (so something like 'C:/tmp/' should still work on windows machines, but the tool should recognize if you pass something like 'rsync://...'). This includes correctly setting permissions on windows machines (which is another issue, I guess)

Kind regards

**Comment by fracpete** [comment]
With commit 51f41baa95344a23d92717c2a9d43dc5b632f1a4, the following example code:

```java
public class PathTest {
  public static void main(String[] args) throws Exception {
    String p;
    p = "rsync://localhost:21234/someDir/";
    System.out.println(p + "\n  " + Binaries.convertPath(p));
    p = "c:\\tmp\\myfile.txt";
    System.out.println(p + "\n  " + Binaries.convertPath(p));
    p = "\\\\host\\share\\myfile.txt";
    System.out.println(p + "\n  " + Binaries.convertPath(p));
    p = "/home/some/where/myfile.txt";
    System.out.println(p + "\n  " + Binaries.convertPath(p));
  }
}
```

Now outputs this (under Windows only!):

```
rsync://localhost:21234/someDir/
  rsync://localhost:21234/someDir/
c:\tmp\myfile.txt
  /cygdrive/c/tmp/myfile.txt
\\host\share\myfile.txt
  \\host\share\myfile.txt
/home/some/where/myfile.txt
  /home/some/where/myfile.txt
```

Will push out a bugfix release shortly.

**Comment by fracpete** [comment]
Release 3.2.7-4 is now available:
https://github.com/fracpete/rsync4j/releases/tag/rsync4j-pom-3.2.7-4

May still take a few hours before artifacts have been sync'ed with Maven Central.

Please give it a go and let me know how you get on. If the problem is solved, then please close this issue. Otherwise, please report back.

**Comment by fcyron** [comment]
Sorry, I closed this too eary.

**Comment by fcyron** [comment]
Just a quick question: I guess, we still need to set special permissions when we use rsync under windows? Or is this handled by your library?

**Comment by fracpete** [comment]
Please clarify what you mean by *special permissions*.

**Comment by fcyron** [comment]
When I transfer a file with rsync from Unix to Windows, I have to add the command line arguments 
"--perms --chmod=a=rwx,Da+x". Otherwise I cannot access the file on the windows filesystem. This has nothing to do with your library per se, I just thought that it would be nice to be able to use your library on both windows and unix systems without having to change my code.

-> I do not know if this can be done in your library as I don't fully understand why this --perms and --chmod is necessary on the windows OS. I just got the solution from stackoverflow and it works. (https://stackoverflow.com/questions/5798807/rsync-on-windows-wrong-permissions-for-created-directories)

**Comment by fcyron** [comment]
The rest of the changes works as expected. I close this ticket.
Thank you for your quick response!
