### ISSUE TITLE
How to detect whether the rsync server can connect？

### ISSUE THREAD

**Issue by 329724814** [fracpete/rsync4j#40]
Just like the tite .
Please help to answer

**Comment by fracpete** [comment]
Example scenario?

**Comment by 329724814** [comment]
The requirement is to configure an rsync server, and then synchronize some data to this rsync server. I hope to add a verification function when configuring the rsync server to verify whether the rsync server can be connected, so as to prompt the front end.

**Comment by fracpete** [comment]
Assuming that the rsync server is a Linux machine that you access via ssh for your rsync commands, you could translate the solutions using `ssh` mentioned [here](https://unix.stackexchange.com/a/478045) to using the [Ssh](https://fracpete.github.io/rsync4j/java/#ssh) class that comes with rsync4j.

**Comment by 329724814** [comment]
But I can’t get the ssh account password, I can only get the rsync related account information.

**Comment by fracpete** [comment]
Well, not having information to go by, I can only guess... A real basic (and not necessarily efficient) way of checking is whether the same command with the [--dry-run/-n](https://github.com/fracpete/rsync4j/blob/a0b49ce2ce88dc349d8d8c7b114b932e4d2c7f78/rsync4j-core/src/main/java/com/github/fracpete/rsync4j/RSync.java#L1142) flag enabled works (ie has exit code 0).

**Comment by 329724814** [comment]
Can i use mkpath to creat dir with this jar?

**Comment by fracpete** [comment]
different question, different issue please. I presume that the other issue has been resolved.

**Comment by 329724814** [comment]
ok, thank you very much

**Comment by 329724814** [comment]
Can you tell me the address of that issue? I can't find it.

**Comment by fracpete** [comment]
Create a new issue on github with your new question.
