### ISSUE TITLE
 Can I use the MkPath command to create the directory of the rsync receiver?

### ISSUE THREAD

**Issue by 329724814** [fracpete/rsync4j#41]

**Comment by fracpete** [comment]
Not directly. But you can use the [additional(...)](https://github.com/fracpete/rsync4j/blob/a0b49ce2ce88dc349d8d8c7b114b932e4d2c7f78/rsync4j-core/src/main/java/com/github/fracpete/rsync4j/RSync.java#L2357) method to set additonal rsync parameters not available through get/set methods.

**Comment by 329724814** [comment]
ok，thank you very much,I will try it

**Comment by fracpete** [comment]
Added with commit 60e3a30bdde2c43badda334b4648d154a132316a

**Comment by fracpete** [comment]
Generally available with release [3.2.7-5](https://github.com/fracpete/rsync4j/releases/tag/rsync4j-pom-3.2.7-5).

**Comment by fracpete** [comment]
assumed to be resolved due to inactivity
