### ISSUE TITLE
rsync failure left with "[rsync] <defunct>" zombie processes

### ISSUE THREAD

**Issue by fachen2015** [fracpete/rsync4j#46]
Hi I use rsync4j-core 3.2.3-7  (processoutput4j 0.0.7) in my project, but encountered this issue. whenever rsync failed (error 11), it would leave a zombie process not properly cleaned up. I double checked the output/err stream processor and could not find any issues there.

Any thoughts on this?
Thanks  
#
![image](https://github.com/user-attachments/assets/1fa1da5d-f90b-4316-82a1-a297d676a2c6)

**Comment by fracpete** [comment]
I haven't encountered an error code 11 before (*Error in file I/O* - [full list of exit codes](https://lxadm.com/rsync-exit-codes/)).

According to this blog post, an error code 11 can often be caused by a full disk:
https://bobcares.com/blog/rsync-error-code-11/

**Comment by fachen2015** [comment]
it's indeed full-disk. this is for a remote fs where striping is used, so a back-off retry would succeed later. However the initial failure would leave a zombie process not properly cleaned up. oneline resources all mention that zombie was caused by not draining out/err stream from the child process, but I do provide the processor for both streams, so wonder if any potential issues in the lib itself.

**Comment by fracpete** [comment]
You could try upgrading [processoutput4j](https://central.sonatype.com/artifact/com.github.fracpete/processoutput4j/overview), as I made a small change today to account for flushing stdout/stderr of a failed process. You may have to upgrade your rsync4j version to the latest one, though.

**Comment by fracpete** [comment]
due to no further feedback, assuming to be fixed (f2613d5f9834104d47826f01bd018db3fc009c6f)

**Comment by fachen2015** [comment]
This is still happening after upgrade. I noticed my current system has hundreds of zombie processes left while the main is still running .
