### ISSUE TITLE
Error while executing rsync with ssh protocol

### ISSUE THREAD

**Issue by rsinet** [fracpete/rsync4j#6]
Hi.

I'm getting error bellow while executing the command:

Command-line: /usr/bin/rsync --verbose --archive --recursive --rsh="ssh -i /Users/roberto/.ssh/id_rsa" --timeout=300000 --compress --exclude=*i.xml  /Users/roberto/linux/aplic/ user@server:temp/roberto/config

ProcessadorSaidaRSync - [ERR] rsync: Failed to exec ssh -i /Users/roberto/.ssh/id_rsa_sepel1_fumaca: No such file or directory (2)
ProcessadorSaidaRSync - [ERR] rsync error: error in IPC code (code 14)
ProcessadorSaidaRSync - [ERR] rsync: connection unexpectedly closed (0 bytes received so far) [sender]
ProcessadorSaidaRSync - [ERR] rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52/rsync/io.c(453) [sender=2.6.9]

I have ssh on $PATH.
Command works on terminal, but not when using rsync4j api.

Could you help me ?

**Comment by fracpete** [comment]
You are using two different identities:
* works: `/Users/roberto/.ssh/id_rsa`
* doesn't work: `/Users/roberto/.ssh/id_rsa_sepel1_fumaca`
Is that the problem?

**Comment by rsinet** [comment]
Sorry. I use The correct id key  id_rsa_sepel1_fumaca.
--rsh="ssh -i /Users/roberto/.ssh/id_rsa"

Strange is if I call from terminal, the exactly command works.

**Comment by fracpete** [comment]
OK. Could you please post the relevant Java code that you use for generating the rsync command? I'll try to have a look at it the next couple of days.

**Comment by fracpete** [comment]
Have you tried using "/usr/bin/ssh -i ..." instead of "ssh -i ..."?

**Comment by rsinet** [comment]
Sorry for the delay.
Yes. I have tried full path command, but doesn't work.

Thats my code:

import com.github.fracpete.processoutput4j.output.StreamingProcessOutput;
import com.github.fracpete.rsync4j.RSync;

public class ExecutorRSync {
	private static Logger logger = LoggerFactory.getLogger("ExecutorRSync");
    private RSync rSync;

    public ExecutorRSync(String caminhoChavePrivadaAutenticacao) {
    	this(-1, caminhoChavePrivadaAutenticacao);
	}

    public ExecutorRSync(Integer timeout, String caminhoChavePrivadaAutenticacao) {
    	this.rSync = new RSync()
    			.additional("")
    			.timeout(timeout)
    			.recursive(true)
    			.archive(true)
    			.compress(true)
    			.verbose(true)
    			.outputCommandline(logger.isInfoEnabled())
    			.rsh("\"ssh -i " + caminhoChavePrivadaAutenticacao + "\"");
	}

	public void executar(String origem, String destino) throws ExcecaoInfraRSync {
		executarComExclusao(origem, destino, null);
    }

    public void executarComExclusao(String origem, String destino, String[] mascaraExclusao) throws ExcecaoInfraRSync {
		StreamingProcessOutput output = new StreamingProcessOutput(new ProcessadorSaidaRSync());
    	try {
    		rSync.source(origem);
    		rSync.destination(destino);
    		if (mascaraExclusao != null && mascaraExclusao.length > 0) {
        		rSync.exclude(mascaraExclusao);
    		}
    		output.monitor(rSync.builder());
		} catch (Exception e) {
			throw new ExcecaoInfraRSync(e);
		} finally {
    		if (output.getExitCode() > 0) {
    			throw ExcecaoInfraRSync.criarExcecaoRSync(output.getExitCode());		
    		}			
		}
    }

}
class ProcessadorSaidaRSync implements StreamingProcessOwner {
	private static Logger logger = LoggerFactory.getLogger("ProcessadorSaidaRSync");

	public StreamingProcessOutputType getOutputType() {
		return StreamingProcessOutputType.BOTH;
	}

	public void processOutput(String line, boolean stdout) {
		logger.info((stdout ? "[OUT] " : "[ERR] ") + line);
	}
}

**Comment by fracpete** [comment]
Remove the double quotes around the `ssh` command.
Instead of `.rsh("\"ssh -i " + caminhoChavePrivadaAutenticacao + "\"")` 
use `.rsh("ssh -i " + caminhoChavePrivadaAutenticacao + ")`

**Comment by rsinet** [comment]
I have already done that. It works but it syncs all files that are in
current context  executing folder. For example, if I run the Java class I
send you inside a JBoss, it syncs all files inside $JBOSS_HOME/bin, such as
run.sh, run.conf, etc.

All tests are done using Eclipse Oxygen. 

Em Ter, 26 de jun de 2018 18:15, Peter Reutemann <notifications@github.com>
escreveu:

**Comment by fracpete** [comment]
I found the problem: the use of an empty `additional` parameter causes this behavior. I've committed a change and will make a new release.

**Comment by rsinet** [comment]
Thats another thing. I had to set empty additional because if I didnt an
nullexception occurs.

Em 26/06/2018 18:28, "Peter Reutemann" <notifications@github.com> escreveu:

I found the problem: the use of an empty additional parameter causes this
behavior. I've committed a change and will make a new release.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fracpete/rsync4j/issues/6#issuecomment-400468386>, or mute
the thread

**Comment by rsinet** [comment]
I will test new changes and report you back.

**Comment by fracpete** [comment]
Release 3.1.2-11 is now available.

**Comment by rsinet** [comment]
Fixed in release 3.1.2-11. Thank you soo much.

**Comment by fracpete** [comment]
Thanks for reporting and testing!
