### ISSUE TITLE
exclude option out of order

### ISSUE THREAD

**Issue by rsinet** [fracpete/rsync4j#7]
Hi.

The include + exclude option is not working. The exclude option must be the last one in arguments command line to work. See code below:

/usr/bin/rsync --verbose --archive --recursive --rsh=/usr/bin/ssh -i /Users/roberto/.ssh/id_rsa_sepel1_fumaca --timeout=300000 --compress --exclude=* --include=*.jpeg --include=*/ /Users/roberto/linux/ user@server:temp/roberto

if exclude is right after includes, it works.

Could you fixed it ?

**Comment by fracpete** [comment]
What version of the library are you using (I remember changing the order; from a pull request)? Please also post your code.

**Comment by rsinet** [comment]
3.1.2-11

**Comment by fracpete** [comment]
And your code, please.

**Comment by rsinet** [comment]
public void executarComInclusao(String origem, String destino, String... mascaraInclusao) throws ExcecaoInfraRSync {
		StreamingProcessOutput output = new StreamingProcessOutput(new ProcessadorSaidaRSync());
    	try {
    		rSync.source(origem);
    		rSync.destination(destino);
    		if (mascaraInclusao != null && mascaraInclusao.length > 0) {
    			List<String> mascara = new ArrayList<String>(Arrays.asList(mascaraInclusao));
        		// para incluir subdiret\u00f3rios
    			mascara.add("*/");
    			String[] mascaraArray = mascara.toArray(new String[mascara.size()]);
        		rSync.include(mascaraArray);
    		}
    		rSync.exclude("*");
    		output.monitor(rSync.builder());
		} catch (Exception e) {
			throw new ExcecaoInfraRSync(e);
		} finally {
    		if (output.getExitCode() > 0) {
    			throw ExcecaoInfraRSync.criarExcecaoRSync(output.getExitCode());
    		}
		}
    }

**Comment by fracpete** [comment]
Should be fixed with release 3.1.2-12. Maven Central is quite slow today, so it may take a while before the artifacts are publicly aviaiable.

**Comment by rsinet** [comment]
Thanks man.

Em qua, 15 de ago de 2018 18:20, Peter Reutemann <notifications@github.com>
escreveu:
