### ISSUE TITLE
How to use Java to build rsync client and connect to rsync --daemon service

### ISSUE THREAD

**Issue by mdzz9527** [fracpete/rsync4j#8]

**Comment by mdzz9527** [comment]
I looked at https://fracpete.github.io/rsync4j/java/, but I still don't understand

**Comment by fracpete** [comment]
Explain in detail what you are trying to achieve.

**Comment by mdzz9527** [comment]
I want to connect to the rsync --daemon service via the Java rsync client

**Comment by fracpete** [comment]
That's not more detailed... What are your source/target machines and directories? How do you want to synchronize the directories? The remote machine is presumably a Linux box with rsync installed?

**Comment by mdzz9527** [comment]
The remote machine is  a Linux box with rsync installed ,started rsync --daemon service ,I want to use the Java rsync client connect.

**Comment by fracpete** [comment]
You still haven't answered my other questions.

**Comment by mdzz9527** [comment]
![image](https://user-images.githubusercontent.com/39895740/50196960-36b46500-0380-11e9-904f-ad2c87a2c71f.png)

**Comment by mdzz9527** [comment]
Are you from New Zealand?Language or cultural differences may make it difficult for us to communicate.

**Comment by fracpete** [comment]
[*I asked three questions and only got an answer to one, hence the reply that you didn't answer my questions*]
You have a double colon in your source (`::`). Usually, you would have an absolute path starting with `/` or a path within the user's home directory starting with `~/`.
What error message are you getting?

**Comment by mdzz9527** [comment]
Host key verification failed.
rsync: did not see server greeting
rsync error: error starting client-server protocol (code 5) at main.c(1666) [Receiver=3.1.2]

**Comment by fracpete** [comment]
Did you generate ssh keys, placed them in `%USERPROFILE%\rsync4j\home\%USERNAME%\.ssh` ([source](https://fracpete.github.io/rsync4j/windows/)) and added the public key to your `known_hosts` on the Linux machine?

**Comment by mdzz9527** [comment]
source is linux's  ,target is windows,
it is rsync config 
[root@dh003 ~]# view /etc/rsync/rsyncd.conf

uid = root
gid = root

use chroot = no

read only = no

write only = no

hosts allow = 192.168.112.40/43 192.168.212.10/200
hosts deny = *

max connections = 5
motd file = /etc/rsync/rsyncd.motd
pid file = /var/run/rsyncd.pid

transfer logging = yes

log format = %t %a %m %f %b

log file = /var/log/rsync.log

timeout = 900
ignore nonreadable = yes

dont compress   = *.gz *.tgz *.zip *.z *.Z *.rpm *.deb *.bz2

[backup]

path = /data/tmp/malong/rsync/

list = no
hosts allow = 192.168.112.40/255.255.255.0  192.168.212.10/255.255.255.0

ignore errors

**Comment by fracpete** [comment]
I'm not gonna be able to look into this in more detail before next week. In the meantime, you could using just plain rsync, without a daemon on the server side.

**Comment by mdzz9527** [comment]
I'm not using SSH to connect. I started rsync --daemon on Linux and then tried to connect to it through a Java program.

**Comment by fracpete** [comment]
rsync4j comes with ssh binaries for Windows. See examples.

**Comment by mdzz9527** [comment]
I'm not using SSH to connect.

**Comment by mdzz9527** [comment]
I want to connect to  rsync server  on Linux

**Comment by fracpete** [comment]
I'm fully aware of that. However, I don't have time configuring a server with rsync/daemon any time soon, hence the rsync/ssh suggestion which works fine (I'm using that on a production server) as a workaround.

**Comment by fracpete** [comment]
Finally had some time to look into this and added a minimal example to the documentation:
https://fracpete.github.io/rsync4j/java/#rsync-daemon

**Comment by Mr-Malone** [comment]
I tested according to your example, but it failed, and there was no data or information.

**Comment by Mr-Malone** [comment]
It still doesn't connect

**Comment by fracpete** [comment]
When testing the rsync daemon setup from my Linux laptop (source), sending data to my server (RPi), I would get an error message if misconfigured something. In case of using the wrong port, I'd get a `Connection refused` in the output. 
How do you monitor the process in your Java code (`StreamingProcessOutput`? `ConsoleOutputProcessOutput`?)? 
What is the error message printed in your Java process to stdout/stderr?

**Comment by mdzz9527** [comment]
I have successfully tested on the Linux platform, but it was my carelessness.Thank you very much for your help. Is there any API documentation for rsync4j?

**Comment by mdzz9527** [comment]
And this is an example of uploading data, what do you do when you download data?

**Comment by fracpete** [comment]
Download: Just swap source and target.
API documentation:
* javadoc on mavem central
* official rsync documentation
* RSync --help (when executed from the command line)
RSync is closely modeled after the options that the rsync binary offers, though not a 100% match possible.

**Comment by mdzz9527** [comment]
I would like to ask, how to get the data stream when transmitting?

**Comment by fracpete** [comment]
Not sure what you mean by data stream. The RSync class merely spawns another process, launching the actual rsync executable. All you can do is capture the output from stdout/stderr (you cannot capture the actual network traffic). This is done by the various monitors in the examples, either in streaming fashion or in bulk at the end. Use the *verbose* option to get information on what files/dirs are being transmitted.

**Comment by mdzz9527** [comment]
I want to get the data stream that is being transmitted synchronously. Do you understand what I mean?

**Comment by fracpete** [comment]
No, the term *data stream* is too generic to know what you mean by that. I just presume that you are referring to the stdout/stderr output that the underlying rsync process generates. You can receive that as it is generated when using the `StreamingProcessOutput` monitor. Check the Java examples.

**Comment by mdzz9527** [comment]
I mean the real data that will be transmitted.

**Comment by fracpete** [comment]
No, you can't. This library is not an implementation of the rsync protocol, it is merely a wrapper around the rsync executable (as the description of this project states). Internally, it constructs a command-line for the rsync executable and executes this as a sub-process. You can only monitor the stdout/stderr output that the sub-process generates.

**Comment by mdzz9527** [comment]
Do you know about the project that java implements the rsync protocol?

**Comment by fracpete** [comment]
Nope.

**Comment by mhtdureja1990** [comment]
> Do you know about the project that java implements the rsync protocol?

Did you find the API that serves this purpose. I am also looking for the same project.
If you have already found it, please let me know.
